"""Simple APIs and lifecycle components for Human-AI alignment research."""

from human_alignment.api import align, load_checkpoint, load_model, run_config
from human_alignment.config import (
    CheckpointConfig,
    DPOConfig,
    GRPOConfig,
    KTOConfig,
    PPOConfig,
    PreferenceDistillationConfig,
    SFTConfig,
    SimPOConfig,
)
from human_alignment.mechanisms.training import (
    ADPA,
    CTPD,
    DCKD,
    DPO,
    GRPO,
    KTO,
    PPD,
    PPO,
    SFT,
    TVKD,
    VPD,
    PreferenceDistillation,
    SimPO,
)
from human_alignment.pipeline import AlignmentPipeline
from human_alignment.results import AlignmentRun, AssuranceReport, PipelineResult
from human_alignment.specification import AlignmentSpecification, Stakeholder
from human_alignment.supervision import (
    InstructionExample,
    KTOExample,
    PreferenceExample,
    PreferenceDistillationExample,
    PromptExample,
    collect_preference_distillation_data,
)
from human_alignment.types import (
    AlignmentStage,
    AlignmentTarget,
    EvaluationCase,
    FeedbackRepresentation,
    FeedbackSource,
    Generation,
    GenerationRequest,
    InteractionContext,
    SupervisionSignal,
    TaxonomyTrace,
)
from human_alignment.workflows import (
    DistillationPreparationConfig,
    PreparedDistillationDataset,
    prepare_preference_distillation_dataset,
)

__all__ = [
    "ADPA",
    "AlignmentPipeline",
    "AlignmentRun",
    "AlignmentSpecification",
    "AlignmentStage",
    "AlignmentTarget",
    "AssuranceReport",
    "CTPD",
    "CheckpointConfig",
    "DCKD",
    "DPO",
    "DPOConfig",
    "DistillationPreparationConfig",
    "EvaluationCase",
    "FeedbackRepresentation",
    "FeedbackSource",
    "GRPO",
    "GRPOConfig",
    "Generation",
    "GenerationRequest",
    "InstructionExample",
    "InteractionContext",
    "KTO",
    "KTOConfig",
    "KTOExample",
    "PPO",
    "PPOConfig",
    "PPD",
    "PipelineResult",
    "PreferenceExample",
    "PreparedDistillationDataset",
    "PreferenceDistillation",
    "PreferenceDistillationConfig",
    "PreferenceDistillationExample",
    "PromptExample",
    "SFT",
    "SFTConfig",
    "SimPO",
    "SimPOConfig",
    "Stakeholder",
    "SupervisionSignal",
    "TaxonomyTrace",
    "TVKD",
    "VPD",
    "align",
    "collect_preference_distillation_data",
    "load_checkpoint",
    "load_model",
    "prepare_preference_distillation_dataset",
    "run_config",
]

__version__ = "0.4.0"
